### ISSUE TITLE
Multiple inventories not allowed to be used on the UUID mode

### ISSUE THREAD

**Issue by koalalord9999** [gigaherz/Enderthing#17]
Minecraft Version 1.10.2 - Mod Version 0.6.11
I'm unable to connect these items to the UUID (middle lock missing) private ender chest:
Mekanism Machines
Mekanism Digital Miner
Mekanism Item Cables
(Probably Mekanism as a whole)
Ender IO Machines (Cables work though)
(+Advanced) Item Collector from Random Things

I'm using All  the Mods Modpack V1.17 (for test environment..?)

**Comment by gigaherz** [comment]
Strange. I'll look into it after work...

**Comment by gigaherz** [comment]
Sorry, work happened. No idea when I'll be able to get back to this.

**Comment by gigaherz** [comment]
I have finally had time to look into this: Mekanism does not appear to support the new capability-based item handler system, so it can't work with this mod. And before you ask, no I will not implement the old system.

As for EnderIO, I was just able to pull from a bound private inventory into an alloy smelter, and push the smelting result into another one, so not sure if it has been fixed since you posted the report.

Random Things is trickier, because it won't work in my development environment. I'll see what I can do tomorrow.

**Comment by gigaherz** [comment]
The Item Collector is also incompatible with the new inventory system. The author of Random things is aware of the issue and said he'll be fixing it someday.

Closing since I did as much as I can from my side.
